### ISSUE TITLE
MDC-101 Need to specify the branch to start

### ISSUE THREAD

**Issue by CristianGM** [material-components/material-components-android-codelabs#1]
The codelab doesn't specify which branch to start, and master is the solution.

**Comment by afohrman** [comment]
In section 2 of the 101 codelabs, there are instructions to check out `101-starter`.

**Comment by CristianGM** [comment]
Are you sure?
https://codelabs.developers.google.com/codelabs/mdc-101-kotlin/#2

the only mention of `101-starter` is if you download the zip
