### ISSUE TITLE
Returns textInputLayout list zero

### ISSUE THREAD

**Issue by RagavendraM** [material-components/material-components-android-codelabs#10]
In For loop List returns Zero

**Comment by cketcham** [comment]
I'm going to need a bit more context to understand this bug. Where is this happening? What exactly is happening? What do you expect to happen instead?

**Comment by cketcham** [comment]
In what case is it returning zero TextInputLayouts? When I run the example (https://github.com/material-components/material-components-android-codelabs/tree/111-complete), it correctly shows errors for all the TextInputLayouts.

Is this a problem when you start with 111-starter and follow the directions in the codelab?

**Comment by david3climas** [comment]
how to translate the outputs into Portuguese from R.string.error_string?
