### ISSUE TITLE
Typo in mdc-103-kotlin

### ISSUE THREAD

**Issue by ColtonIdle** [material-components/material-components-android-codelabs#11]
> This is the third of 4 codelabs that will guide you through building an app called Shrine, an e-commerce website that sells clothing and home goods.The related codelabs can be found at:MDC-101: Material Components (MDC) BasicsMDC-102: Material Design Structure and LayoutMDC-104: Material Design Advanced ComponentsBy the end of MDC 104, you'll build a **website** that looks like this:

We're building an app, not a website. Typo I assume?

**Comment by afohrman** [comment]
Thanks for filing this issue. We fixed the typo.
