### ISSUE TITLE
Typo in MDC-103 Android: Material Theming with Color, Elevation and Type (Kotlin)

### ISSUE THREAD

**Issue by ColtonIdle** [material-components/material-components-android-codelabs#12]
https://codelabs.developers.google.com/codelabs/mdc-103-kotlin/index.html?index=..%2F..%2Findex#5

>We'll also need to make a small change to our product_grid_fragment.xml to remove the paddings from our NestedScrollView, as follows:

`product_grid_fragment.xml` should be `shr_product_grid_fragment.xml`

**Comment by afohrman** [comment]
Thanks for filing this issue. We fixed the typo.
