### ISSUE TITLE
README links to a dead url

### ISSUE THREAD

**Issue by ColtonIdle** [material-components/material-components-android-codelabs#14]
>Material Components for Android are modular and customizable UI components that implement Material Design. This repo houses the source for the Building Beautiful Apps Faster codelab.

This repository is structured as branches. You can checkout an individual branch by running git checkout 101-starter or the equivalent for the codelab you are following.

There are some simple scripts for maintaining this repository in the tools/ directory.

`Building Beautiful Apps Faster` links you to a site that says "Unavailable
This codelab is unavailable. For other great Material Design resources, see material.io."

**Comment by afohrman** [comment]
Thanks for the feedback. This has now been fixed.
