### ISSUE TITLE
Source code for MDC-104 Android: Material Advanced Components (Kotlin) doesn't build

### ISSUE THREAD

**Issue by ColtonIdle** [material-components/material-components-android-codelabs#15]
https://codelabs.developers.google.com/codelabs/mdc-104-kotlin/index.html?index=..%2F..%2Findex#1

When you download the source there is an extra import that causes the build to fail.

In `ProductGridFragment.kt` the line `import com.google.codelabs.mdc.java.shrine.ProductGridItemDecoration` should be removed.

Then everything builds fine.

**Comment by cketcham** [comment]
Thanks! Removed that import from the code
