### ISSUE TITLE
Typo in MDC-111 Android: Incorporating Material Components into your codebase (Kotlin)

### ISSUE THREAD

**Issue by ColtonIdle** [material-components/material-components-android-codelabs#16]
https://codelabs.developers.google.com/codelabs/mdc-111-kotlin/index.html?index=..%2F..%2Findex#3

> MDC Buttons are a simple plug-and-play component. You just replace the XML component name Button with MaterialButton, and apply the default MaterialButton.

Apply the default MaterialButton... theme?

**Comment by afohrman** [comment]
Thanks for reporting this typo. I fixed in the Kotlin and Java 111 codelabs. The fix should now be live.
