### ISSUE TITLE
Issue reporting bug for a codelab

### ISSUE THREAD

**Issue by ColtonIdle** [material-components/material-components-android-codelabs#17]
I'm working on the codelab "Build Your First Android App in Kotlin"

https://codelabs.developers.google.com/codelabs/build-your-first-android-app-kotlin/index.html?index=..%2F..%2Findex#3

If I click "Did you find a mistake? Please file a bug." it takes me to a google form https://docs.google.com/a/google.com/forms/d/e/1FAIpQLSdG8IaxfyJT31833Tub2Gtbq3EcZ4o4ubPWXg_B1KBzfh9NCA/viewform with "You need permission
This form can only be viewed by users in the owner's organization.

Try contacting the owner of the form if you think this is a mistake. Learn More."

I figure someone here would be able to help even though it's not a material-component issue.

**Comment by afohrman** [comment]
Thanks, I passed this feedback along to the codelab authors.
