### ISSUE TITLE
Failed to find target with hash string android-p install missing platforms

### ISSUE THREAD

**Issue by alexmanrique** [material-components/material-components-android-codelabs#19]
Any idea why I get this error in android studio when gradle build runs with your repository?https://stackoverflow.com/questions/50826588/failed-to-find-target-with-hash-string-android-p-install-missing-platforms-a

thanks

**Comment by Tibevilaqua** [comment]
Yep, you're trying to find a SDK that corresponds to the version "android-p"
have a look at your build.gradle file:

android {
    compileSDKVersion 'android-p'
    ..........
}
change it to 
android {
    compileSDKVersion 28 (for example)
    ..........
}

that should do it.

**Comment by manchoydotid** [comment]
Hi @Tibevilaqua , There's no "compileSDKVersion" on build.gradle file.

![no_compile_sdk](https://user-images.githubusercontent.com/3701920/41546620-5845b516-7348-11e8-8282-2275651b2240.JPG)

**Comment by Tibevilaqua** [comment]
inside the app folder.
https://github.com/material-components/material-components-android-codelabs/blob/master/java/shrine/app/build.gradle

**Comment by manchoydotid** [comment]
@Tibevilaqua  Ahh, It works. Thank you

**Comment by cketcham** [comment]
Updated the code to use 28

**Comment by riturajgc** [comment]
Thanks @Tibevilaqua your comment above helped a lot.
