### ISSUE TITLE
Multi-line app bar title

### ISSUE THREAD

**Issue by unomonteiro** [material-components/material-components-android-codelabs#21]
**Describe the bug**
This bug should be a feature request.
As per Material [anatomy of the top App bar](https://material.io/design/components/app-bars-top.html#anatomy): 
![image](https://user-images.githubusercontent.com/7604348/43137820-d01d53b0-8f44-11e8-9875-3ab0fdad3eb0.png)

> Do.
> If title text is long, use a prominent app bar and wrap the title to two lines.

**To Reproduce**
Currently the codelabs only explain how to set the title and color

**Expected behavior**
Codelabs should explain how to wrap the title to two lines.

**Screenshots**

**Codelab details (please complete the following information about the codelab):**
 - Level (MDC-101, MDC-102, MDC-103, MDC-104, or MDC-111)
 - Language (Java or Kotlin)
 - Link to the codelab at the step with the issue
https://codelabs.developers.google.com/codelabs/mdc-102-java/#2

**Additional context**

**Comment by gsajith** [comment]
Hello!

Our codelabs have pretty strict guidelines for consistency across platforms (as similar codelabs exist for iOS and web). 

I believe this feature request should actually go to our main library, and we can add this as a demo in our catalog app. Could you file a bug with this request at https://issuetracker.google.com/issues/new?component=439535 ?

Thanks!
