### ISSUE TITLE
MDC-101 kotlin: Error In ImageRequester.kt

### ISSUE THREAD

**Issue by Dochomorka** [material-components/material-components-android-codelabs#28]
**Describe the bug**
MDC-101 Kotlin: build error  (Unresolved reference: displayMetrics)

**To Reproduce**
1. Go to **network** package
2. Click on **ImageRequester.kt**
3. Scroll down to **calculateMaxByteSize(context: Context)** function

**Expected behavior**
build finished successfully

**Screenshots**
[https://drive.google.com/file/d/15EMFG3SR5SLtFThlXVX7ibrAEz0RKZ1y/view?usp=sharing](url)
[https://drive.google.com/file/d/0B_bfXO9nDogtVFpacHNsVXNydktQMDBMUDJjRk9ZN3dDdWlF/view?usp=sharing](url)

**Codelab details **
 - Level (MDC-101)
 - Language (Kotlin)
 - Link to the codelab at the step with the issue 
[https://github.com/material-components/material-components-android-codelabs
](url)

**Comment by ikim24** [comment]
In your screenshot, it looks like the following line 58 has been edited. It should be:
        val displayMetrics = context.resources.displayMetrics
