### ISSUE TITLE
Dead Link

### ISSUE THREAD

**Issue by ashrafi** [material-components/material-components-android-codelabs#30]
**Describe the bug**
In this codelab you'll use the default components provided by MDC Android. You'll learn to customize them in **_MDC 103: Material Design Theming with Color, Shape, Elevation and Type_**.
is a dead link

**To Reproduce**
1. Go to https://codelabs.developers.google.com/codelabs/mdc-101-kotlin/#0
3. Scroll down to MDC Android components in this codelab
2. Click on  **MDC 103: Material Design Theming with Color, Shape, Elevation and Type.**
4. See error [http://go/mdc-103](http://go/mdc-103) is a dead page

**Expected behavior**
live page

**Codelab details (please complete the following information about the codelab):**
 - Level (MDC-101
 - Language Kotlin)
 - Link to the codelab at the step with the issue (ex: 
https://codelabs.developers.google.com/codelabs/mdc-101-kotlin/#0 
MDC Android components in this codelab

**Comment by cketcham** [comment]
fixed
