### ISSUE TITLE
Material shape element lost shadow when shape color has alpha like (#F0FFFFFF)

### ISSUE THREAD

**Issue by Jerry805** [material-components/material-components-android-codelabs#32]
Material shape element lost shadow when shape color has alpha like (#F0FFFFFF)

Android studio 3.3
Material 1.1.0-alpha02
Kotlin

1. create a material card view in layout
2. create a shape. like round. set the shape color with alpha not ff
4. set background of the card view in MainActivity.kt
5. run app and would see that shadow disappears. when set shape color without alpha, shadow displays as expected.

**Comment by afohrman** [comment]
Thanks for reporting this issue. This sounds like a bug in the MDC Android library; could you please file an issue at https://issuetracker.google.com/issues/new?component=439535 so that we can take a look?
