### ISSUE TITLE
MDC-104-kotlin-starter project dependency conflict.

### ISSUE THREAD

**Issue by vikaspatidar** [material-components/material-components-android-codelabs#34]
MDC-104 Starter project for both Java and Kotlin added an api dependency for the Material library.
`api 'com.google.android.material:material:1.1.0-alpha05'` but the tutorial ask for adding another dependency for the `api 'com.android.support:design:28.0.0-alpha3'` in `build.gradle`. Please check [**Add project dependencies**](https://codelabs.developers.google.com/codelabs/mdc-104-java/#1) section. This causes conflict while adding the dependencies. Also some button in login screen are from `com.google.android.material` package but in tutorial some xml layout has buttons from the `android.support.design.button` package. Please check the xml code for the layout file [shr_backdrop.xml](https://codelabs.developers.google.com/codelabs/mdc-104-java/#2). This could result in crashes at runtime.
Thanks

**Comment by gsajith** [comment]
Thanks for reporting this. I've filed https://issuetracker.google.com/issues/131624989 to track this issue, please follow the bug there for updates on when this is fixed.
