### ISSUE TITLE
MDC-102 Java - Android Studio warning for textAppearance xml resource marked as private

### ISSUE THREAD

**Issue by ashwanth1109** [material-components/material-components-android-codelabs#4]
![image](https://user-images.githubusercontent.com/32328857/39840234-4b3f8e98-53fc-11e8-886e-51274976fe0f.png)

As shown in the image, I'm getting a warning that the resource 'android:textAppearance="?attr/textAppearanceHeadline6" is marked private in com.android.support:design-widget. To fix this copy the resource into your own project instead.

**Comment by cketcham** [comment]
This is a bug with the public attrs exposed by the library and will be fixed in the next release.
