### ISSUE TITLE
Product images fail to load

### ISSUE THREAD

**Issue by giladnavefrost** [material-components/material-components-android-codelabs#80]
When progressing through the tutorials and after step 5 of tutorial MDC-102 (https://codelabs.developers.google.com/codelabs/mdc-102-java#4), a run time unexpected response is received from imageRequester.setImageFromUrl(holder.productImage, product.url); in the ProductCardRecyclerViewAdapter.java class:
"
E/Volley: [172] BasicNetwork.performRequest: Unexpected response code 404 for https://storage.googleapis.com/material-vignettes.appspot.com/image/0-0.jpg
E/Volley: [173] BasicNetwork.performRequest: Unexpected response code 404 for https://storage.googleapis.com/material-vignettes.appspot.com/image/2-0.jpg
E/Volley: [174] BasicNetwork.performRequest: Unexpected response code 404 for https://storage.googleapis.com/material-vignettes.appspot.com/image/1-0.jpg
"

The UI remains without the images at this point:
![image](https://user-images.githubusercontent.com/91655631/141757456-22201b9e-7f79-4dc8-a37a-d87e3e264bee.png)

It seems that the listed urls of the product images under products.json were removed or revised in such a way that causes this malfunction.

Trying to access the url itself from a browser return with this error:
"
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchBucket</Code>
<Message>The specified bucket does not exist.</Message>
</Error>
"

Any advise or update on this topic is appreciated.

**Comment by gabrielle-cozart** [comment]
Also getting the same issue. Looks like the storage bucket was removed?

**Comment by giladnavefrost** [comment]
@gabrielle-cozart this sure can be the case. I would expect that if some resource is removed or renamed to another location, it would be mentioned or updated through the code lab guide. Otherwise it is hard to know if it is a case of resource removal as you suggest or a local bug in local project or environment.
In case we can get a more official comment on that it would be great.

**Comment by ayoubcamali** [comment]
the same problem

**Comment by SinitBar** [comment]
this is exactly the problem with internet resources of images (even **https://storage.googleapis.com** is bad). If you try to copy and paste some another url for the image instead of url into products.json (first check your new url works: paste into internet, you sould see an image, nothing else), it will work. It worked for me, so you could check like this too, one url is enough.

**Comment by giladnavefrost** [comment]
Totally agree @SinitBar with your inputs. Hope that the owner of this code lab would fix these broken links or at least update on this issue on the code lab pages so others won't fight for nothing when this is not a local dev environment issue.
